using Hexa.NET.GLFW;

namespace DTXMania.Core.Glue;

public class SlimDXGLFWGlue
{
    public static SlimDX.DirectInput.Key GLFWKeyToSlimDXKey(GlfwKey key)
    {
        switch (key)
        {
            case GlfwKey.Unknown:
                return SlimDX.DirectInput.Key.Unknown;
            case GlfwKey.Space:
                return SlimDX.DirectInput.Key.Space;
            case GlfwKey.Apostrophe:
                return SlimDX.DirectInput.Key.Apostrophe;
            case GlfwKey.Comma:
                return SlimDX.DirectInput.Key.Comma;
            case GlfwKey.Minus:
                return SlimDX.DirectInput.Key.Minus;
            case GlfwKey.Period:
                return SlimDX.DirectInput.Key.Period;
            case GlfwKey.Slash:
                return SlimDX.DirectInput.Key.Slash;
            case GlfwKey.Key0:
                return SlimDX.DirectInput.Key.D0;
            case GlfwKey.Key1:
                return SlimDX.DirectInput.Key.D1;
            case GlfwKey.Key2:
                return SlimDX.DirectInput.Key.D2;
            case GlfwKey.Key3:
                return SlimDX.DirectInput.Key.D3;
            case GlfwKey.Key4:
                return SlimDX.DirectInput.Key.D4;
            case GlfwKey.Key5:
                return SlimDX.DirectInput.Key.D5;
            case GlfwKey.Key6:
                return SlimDX.DirectInput.Key.D6;
            case GlfwKey.Key7:
                return SlimDX.DirectInput.Key.D7;
            case GlfwKey.Key8:
                return SlimDX.DirectInput.Key.D8;
            case GlfwKey.Key9:
                return SlimDX.DirectInput.Key.D9;
            case GlfwKey.Semicolon:
                return SlimDX.DirectInput.Key.Semicolon;
            case GlfwKey.Equal:
                return SlimDX.DirectInput.Key.Equals;
            case GlfwKey.A:
                return SlimDX.DirectInput.Key.A;
            case GlfwKey.B:
                return SlimDX.DirectInput.Key.B;
            case GlfwKey.C:
                return SlimDX.DirectInput.Key.C;
            case GlfwKey.D:
                return SlimDX.DirectInput.Key.D;
            case GlfwKey.E:
                return SlimDX.DirectInput.Key.E;
            case GlfwKey.F:
                return SlimDX.DirectInput.Key.F;
            case GlfwKey.G:
                return SlimDX.DirectInput.Key.G;
            case GlfwKey.H:
                return SlimDX.DirectInput.Key.H;
            case GlfwKey.I:
                return SlimDX.DirectInput.Key.I;
            case GlfwKey.J:
                return SlimDX.DirectInput.Key.J;
            case GlfwKey.K:
                return SlimDX.DirectInput.Key.K;
            case GlfwKey.L:
                return SlimDX.DirectInput.Key.L;
            case GlfwKey.M:
                return SlimDX.DirectInput.Key.M;
            case GlfwKey.N:
                return SlimDX.DirectInput.Key.N;
            case GlfwKey.O:
                return SlimDX.DirectInput.Key.O;
            case GlfwKey.P:
                return SlimDX.DirectInput.Key.P;
            case GlfwKey.Q:
                return SlimDX.DirectInput.Key.Q;
            case GlfwKey.R:
                return SlimDX.DirectInput.Key.R;
            case GlfwKey.S:
                return SlimDX.DirectInput.Key.S;
            case GlfwKey.T:
                return SlimDX.DirectInput.Key.T;
            case GlfwKey.U:
                return SlimDX.DirectInput.Key.U;
            case GlfwKey.V:
                return SlimDX.DirectInput.Key.V;
            case GlfwKey.W:
                return SlimDX.DirectInput.Key.W;
            case GlfwKey.X:
                return SlimDX.DirectInput.Key.X;
            case GlfwKey.Y:
                return SlimDX.DirectInput.Key.Y;
            case GlfwKey.Z:
                return SlimDX.DirectInput.Key.Z;
            case GlfwKey.LeftBracket:
                return SlimDX.DirectInput.Key.LeftBracket;
            case GlfwKey.Backslash:
                return SlimDX.DirectInput.Key.Backslash;
            case GlfwKey.RightBracket:
                return SlimDX.DirectInput.Key.RightBracket;
            case GlfwKey.GraveAccent:
                return SlimDX.DirectInput.Key.Grave;
            case GlfwKey.World1:
                return SlimDX.DirectInput.Key.Oem102; // best-effort mapping for non-US key
            case GlfwKey.World2:
                return SlimDX.DirectInput.Key.Unknown;
            case GlfwKey.Escape:
                return SlimDX.DirectInput.Key.Escape;
            case GlfwKey.Enter:
                return SlimDX.DirectInput.Key.Return;
            case GlfwKey.Tab:
                return SlimDX.DirectInput.Key.Tab;
            case GlfwKey.Backspace:
                return SlimDX.DirectInput.Key.Backspace;
            case GlfwKey.Insert:
                return SlimDX.DirectInput.Key.Insert;
            case GlfwKey.Delete:
                return SlimDX.DirectInput.Key.Delete;
            case GlfwKey.Right:
                return SlimDX.DirectInput.Key.RightArrow;
            case GlfwKey.Left:
                return SlimDX.DirectInput.Key.LeftArrow;
            case GlfwKey.Down:
                return SlimDX.DirectInput.Key.DownArrow;
            case GlfwKey.Up:
                return SlimDX.DirectInput.Key.UpArrow;
            case GlfwKey.PageUp:
                return SlimDX.DirectInput.Key.PageUp;
            case GlfwKey.PageDown:
                return SlimDX.DirectInput.Key.PageDown;
            case GlfwKey.Home:
                return SlimDX.DirectInput.Key.Home;
            case GlfwKey.End:
                return SlimDX.DirectInput.Key.End;
            case GlfwKey.CapsLock:
                return SlimDX.DirectInput.Key.CapsLock;
            case GlfwKey.ScrollLock:
                return SlimDX.DirectInput.Key.ScrollLock;
            case GlfwKey.NumLock:
                return SlimDX.DirectInput.Key.NumberLock;
            case GlfwKey.PrintScreen:
                return SlimDX.DirectInput.Key.PrintScreen;
            case GlfwKey.Pause:
                return SlimDX.DirectInput.Key.Pause;
            case GlfwKey.F1:
                return SlimDX.DirectInput.Key.F1;
            case GlfwKey.F2:
                return SlimDX.DirectInput.Key.F2;
            case GlfwKey.F3:
                return SlimDX.DirectInput.Key.F3;
            case GlfwKey.F4:
                return SlimDX.DirectInput.Key.F4;
            case GlfwKey.F5:
                return SlimDX.DirectInput.Key.F5;
            case GlfwKey.F6:
                return SlimDX.DirectInput.Key.F6;
            case GlfwKey.F7:
                return SlimDX.DirectInput.Key.F7;
            case GlfwKey.F8:
                return SlimDX.DirectInput.Key.F8;
            case GlfwKey.F9:
                return SlimDX.DirectInput.Key.F9;
            case GlfwKey.F10:
                return SlimDX.DirectInput.Key.F10;
            case GlfwKey.F11:
                return SlimDX.DirectInput.Key.F11;
            case GlfwKey.F12:
                return SlimDX.DirectInput.Key.F12;
            case GlfwKey.F13:
                return SlimDX.DirectInput.Key.F13;
            case GlfwKey.F14:
                return SlimDX.DirectInput.Key.F14;
            case GlfwKey.F15:
                return SlimDX.DirectInput.Key.F15;
            // GLFW defines F16..F25, but SlimDX Key enum here goes up to F15; map higher function keys to Unknown
            case GlfwKey.F16:
            case GlfwKey.F17:
            case GlfwKey.F18:
            case GlfwKey.F19:
            case GlfwKey.F20:
            case GlfwKey.F21:
            case GlfwKey.F22:
            case GlfwKey.F23:
            case GlfwKey.F24:
            case GlfwKey.F25:
                return SlimDX.DirectInput.Key.Unknown;
            case GlfwKey.Kp0:
                return SlimDX.DirectInput.Key.NumberPad0;
            case GlfwKey.Kp1:
                return SlimDX.DirectInput.Key.NumberPad1;
            case GlfwKey.Kp2:
                return SlimDX.DirectInput.Key.NumberPad2;
            case GlfwKey.Kp3:
                return SlimDX.DirectInput.Key.NumberPad3;
            case GlfwKey.Kp4:
                return SlimDX.DirectInput.Key.NumberPad4;
            case GlfwKey.Kp5:
                return SlimDX.DirectInput.Key.NumberPad5;
            case GlfwKey.Kp6:
                return SlimDX.DirectInput.Key.NumberPad6;
            case GlfwKey.Kp7:
                return SlimDX.DirectInput.Key.NumberPad7;
            case GlfwKey.Kp8:
                return SlimDX.DirectInput.Key.NumberPad8;
            case GlfwKey.Kp9:
                return SlimDX.DirectInput.Key.NumberPad9;
            case GlfwKey.KpDecimal:
                return SlimDX.DirectInput.Key.NumberPadPeriod;
            case GlfwKey.KpDivide:
                return SlimDX.DirectInput.Key.NumberPadSlash;
            case GlfwKey.KpMultiply:
                return SlimDX.DirectInput.Key.NumberPadStar;
            case GlfwKey.KpSubtract:
                return SlimDX.DirectInput.Key.NumberPadMinus;
            case GlfwKey.KpAdd:
                return SlimDX.DirectInput.Key.NumberPadPlus;
            case GlfwKey.KpEnter:
                return SlimDX.DirectInput.Key.NumberPadEnter;
            case GlfwKey.KpEqual:
                return SlimDX.DirectInput.Key.NumberPadEquals;
            case GlfwKey.LeftShift:
                return SlimDX.DirectInput.Key.LeftShift;
            case GlfwKey.LeftControl:
                return SlimDX.DirectInput.Key.LeftControl;
            case GlfwKey.LeftAlt:
                return SlimDX.DirectInput.Key.LeftAlt;
            case GlfwKey.LeftSuper:
                return SlimDX.DirectInput.Key.LeftWindowsKey;
            case GlfwKey.RightShift:
                return SlimDX.DirectInput.Key.RightShift;
            case GlfwKey.RightControl:
                return SlimDX.DirectInput.Key.RightControl;
            case GlfwKey.RightAlt:
                return SlimDX.DirectInput.Key.RightAlt;
            case GlfwKey.RightSuper:
                return SlimDX.DirectInput.Key.RightWindowsKey;
            case GlfwKey.Menu:
                return SlimDX.DirectInput.Key.Applications;
            default:
                throw new ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }
}